name: Build package
description: Builds a package
inputs:
  package:
    description: Name of the package
    required: true
  dependencies:
    description: List of dependencies
    required: true
    default: ''

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download dependencies artifacts
      if: ${{ inputs.dependencies != '' }}
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.dependencies }}
        path: ./.cache

    - name: Install dependencies from local tarballs
      if: ${{ inputs.dependencies != '' }}
      shell: bash
      run: |
        for package in $(ls ./.cache/*.tgz); do
          npm install "$package"
        done

    - name: Install dependencies from npm
      shell: bash
      run: npm install

    - name: Build package
      shell: bash
      run: npm run build

    # Package each component in ./lib into a .tgz tarball - TODO: Fix for multiple packages in lib
    - name: Package lib
      shell: bash    
      run: |
        cd ./lib
        for dir in */; do
          cd "$dir"
          npm pack
          cd ..
        done

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.package }}
        path: ./lib/*.tgz
