name: Build package
description: Builds a package
inputs:
  package:
    description: Name of the package
    required: true
  dependencies:
    description: List of dependencies
    required: true
    default: ''

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Sanitize dependencies
      if: ${{ inputs.dependencies != '' }}
      id: sanitize-dependencies
      run: |
        SANITIZED_DEPENDENCIES=$(echo "${{ inputs.dependencies }}" | sed 's/@//g' | sed 's/\//-/g')
        echo "sanitized_dependencies=$SANITIZED_DEPENDENCIES" >> $GITHUB_OUTPUT

    - name: Download dependencies artifacts
      if: ${{ inputs.dependencies != '' }}
      uses: actions/download-artifact@v4
      with:
        name: ${{ steps.sanitize-dependencies.outputs.sanitized_dependencies }}
        path: ./.cache

    - name: Install dependencies from local tarballs
      if: ${{ inputs.dependencies != '' }}
      shell: bash
      run: |
        for package in $(ls ./.cache/*.tgz); do
          npm install "$package"
        done

    - name: Install dependencies from npm
      shell: bash
      run: npm install

    - name: Build package
      shell: bash
      run: npm run build

    # Package each component in ./lib into a .tgz tarball - TODO: Handle single and multiple packages
    - name: Package lib
      shell: bash    
      run: |
        cd ./lib
        for dir in */; do
          cd "$dir"
          npm pack
          mv *.tgz ../
          cd ..
        done

    - name: Sanitize package name
      shell: bash
      id: sanitize
      run: |
        SANITIZED_NAME=$(echo "${{ inputs.package }}" | sed 's/@//g' | sed 's/\//-/g')
        echo "sanitized_name=$SANITIZED_NAME" >> $GITHUB_OUTPUT

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.sanitize.outputs.sanitized_name }}
        path: ./lib/*.tgz
