name: Patch package.json with local dependencies
description: Modifies the current package.json to point to local repositories instead
inputs:
  path:
    description: Root directory of the package that should be updated
    required: true
  tarball-dir:
    description: Path to the directory containing the local tarballs
    required: true
    default: './.build-cache'
runs:
  using: 'node20'
  main: 'index.js'
