name: "Patch package.json with local dependencies"
description: "Modifies the current package.json to point to local repositories instead"
inputs:
  path:
    description: "Root directory of the package that should be updated"
    required: true
  type:
    description: 'How the dependencies should change. Possible values: "local" (to consume local tarballs), and "next" (to consume from pre-release CodeArtifact)'
    default: "local"
    required: false
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: INPUT_PATH=${{ inputs.path }} INPUT_TYPE=${{ inputs.type }} node ${{ github.action_path }}/local.mjs
      shell: bash
