name: "Publish package to internal CodeArtifact"
description: "Publishes the current package to an internal CodeArtifact on a pre-release tag"
inputs:
  publish-packages:
    # Arrays are not supported: https://github.com/community/community/discussions/11692
    description: "Comma-separated list of sub-folders to publish"
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Define new version suffix
      id: vars
      run: echo "::set-output name=version_suffix::-next-build.$(git rev-parse --short HEAD)"
      shell: bash

    - run: node ${{ github.action_path }}/index.mjs
      shell: bash
      env:
        INPUT_PATH: ${{ github.workspace }}
        INPUT_SUFFIX: ${{ steps.vars.outputs.version_suffix }}
        PUBLISH_PACKAGES: ${{ inputs.publish-packages }}
        COMMIT_SHA: ${{ github.sha }}
