name: Upload artifact to GitHub Artifacts
description: Compress and uploaded a given folder as an artifact to GitHub Artifacts
inputs:
  path:
    type: string
    description: A file, directory or wildcard pattern that describes what to upload
    required: true
  name:
    type: string
    description: Artifact name
    required: true

runs:
  using: composite
  steps:
    - name: Create artifact
      run: |
        tar -zcvf ${{ inputs.name }}.tar.gz ${{ inputs.path }}
      shell: bash
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.name }}.tar.gz
