name: Build level

on:
  workflow_call:
    inputs:
      packages:
        description: Comma-separated list of packages to build
        required: true
        type: string
      dependencies:
        required: false
        type: string
        default: ''

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(inputs.packages) }}
    steps:
      - name: Build package
        if: ${{ matrix.package != 'cloudscape-design/components' }}
        uses: cloudscape-design/actions/.github/actions/build-package@dry-run
        with:
          package: ${{ matrix.package }}
          dependencies: ${{ inputs.dependencies }}

  build-test-components:
    uses: cloudscape-design/actions/.github/workflows/build-test-components.yml@dry-run
    with:
      dependencies: ${{ inputs.dependencies }}
      skip_lint: true

        