# This workflow executes a full dry-run test, which means that all we build and test all @cloudscape-design packages in GitHub.
# This ensures that the changes in the current package do not cause any regressions for its consumers.
name: build-components

on:
  pull_request:
    branches:
      - main
  workflow_call:

permissions:
  contents: read

defaults:
  run:
    shell: bash

env:
  # Disable Husky in CI
  # https://typicode.github.io/husky/how-to.html#ci-server-and-docker
  HUSKY: 0

jobs:
  buildComponents:
    name: Build components
    runs-on: ubuntu-latest
    steps:
      - uses: cloudscape-design/actions/.github/actions/build-package@artifacts-v4
        with:
          package: cloudscape-design/components
          skip_tests: true

  unitTest:
    name: Components unit tests
    runs-on: ubuntu-latest
    needs:
      - buildComponents
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: cloudscape-design/components
          path: cloudscape-design/components
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Restore cached lib folder
        uses: actions/cache@v4
        with:
          path: cloudscape-design/components/lib
          key: ${{ runner.os }}-lib-cloudscape-design/components-${{ github.sha }}
      - name: Install dependencies from local tarballs
        working-directory: cloudscape-design/components
        run: |
          for package in $(ls ${{ steps.download-artifacts.outputs.download-path }}/*.tgz); do
            echo "Installing $package"
            npm install --no-save "$package"
          done
      - name: Install dependencies from npm
        working-directory: cloudscape-design/components
        run: npm install
      - name: Run Unit Tests
        working-directory: cloudscape-design/components
        run: npm run test:unit
