# This workflow executes a full dry-run test, which means that all we build and test all @cloudscape-design packages in GitHub.
# This ensures that the changes in the current package do not cause any regressions for its consumers.
name: build-components

on:
  pull_request:
    branches:
      - main
  workflow_call:

permissions:
  contents: read

defaults:
  run:
    shell: bash

env:
  # Disable Husky in CI
  # https://typicode.github.io/husky/how-to.html#ci-server-and-docker
  HUSKY: 0

jobs:
  buildComponents:
    name: Build components
    runs-on: ubuntu-latest
    steps:
      - uses: cloudscape-design/actions/.github/actions/build-package@artifacts-v4
        with:
          package: cloudscape-design/components
          skip_tests: false
          cache_working_directory: true

  unitTest:
    name: Components unit tests
    runs-on: ubuntu-latest
    needs:
      - buildComponents
    steps:
      - name: Restore cached working directory
        uses: actions/cache@v4
        with:
          key: cloudscape-design/components-${{ github.sha }}
          path: .
      - name: Run Unit Tests
        run: npm run test:unit
