name: Deploy

on:
  workflow_call:
    inputs:
      artifact-name:
        type: string
        description: Name of artifact to deploy
        required: true
      deployment-path:
        type: string
        description: Directory of assets to upload
        default: '.'

permissions:
  id-token: write
  contents: read
  deployments: write

jobs:
  deploy:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    continue-on-error: true
    environment:
      name: ${{ inputs.artifact-name }}
      url: ${{ steps.deploy.outputs.preview-url }}index.html
    steps:
      - name: Download artifact
        uses: cloudscape-design/actions/.github/actions/download-artifact@main
        with:
          name: ${{ inputs.artifact-name }}
          path: build
      - name: Deploy dev-pages
        id: deploy
        uses: cloudscape-design/actions/.github/actions/deploy-static@main
        with:
          role-to-assume: ${{ secrets.AWS_PREVIEW_ROLE_ARN }}
          deployment-bucket: ${{ secrets.AWS_PREVIEW_BUCKET_NAME }}
          source-path: build/${{ inputs.deployment-path }}
          target-path: ${{ inputs.artifact-name }}
