# This workflow executes a custom dry-run for chat board-components-package
name: dry-run

on:
  pull_request:
    branches:
      - main
  workflow_call:

permissions:
  contents: read

defaults:
  run:
    shell: bash

env:
  # Disable Husky in CI
  # https://typicode.github.io/husky/how-to.html#ci-server-and-docker
  HUSKY: 0

jobs:
  buildCodeView:
    name: Build code view components
    runs-on: ubuntu-latest
    steps:
      - uses: cloudscape-design/actions/.github/actions/build-repository@main
        with:
          repository: cloudscape-design/code-view

  demosTest:
    name: Demos tests
    runs-on: ubuntu-latest
    needs:
      - buildCodeView
    steps:
      - name: Build
        uses: cloudscape-design/actions/.github/actions/build-repository@main
        with:
          repository: cloudscape-design/demos
