# This workflow executes a full dry-run test, which means that all we build and test all @cloudscape-design packages in GitHub.
# This ensures that the changes in the current package do not cause any regressions for its consumers.
name: dry-run-new

on:
  pull_request:
    branches:
      - main
  workflow_call:

permissions:
  contents: read

defaults:
  run:
    shell: bash

env:
  # Disable Husky in CI
  # https://typicode.github.io/husky/how-to.html#ci-server-and-docker
  HUSKY: 0

jobs:
  createBuildTree:
    name: Create build tree
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix-output.outputs.matrix }}    
    steps:
      - uses: cloudscape-design/actions/.github/actions/create-build-tree@dry-run
        id: set-matrix-output
        with:
          package: ${{ github.event.repository.full_name }}
  build:
    needs: createBuildTree
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.createBuildTree.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download dependencies artifacts
        if: ${{ matrix.level > 0 }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ join(needs.createBuildTree.outputs.matrix.*.package, ',') }}
          path: ./.cache

      - name: Install dependencies from local tarballs
        if: ${{ matrix.level > 0 }}
        run: |
          for package in $(ls ./.cache/*.tgz); do
            npm install "$package"
          done

      - name: Install remaining dependencies from npm
        run: npm install

      - name: Build package
        run: npm run build

      # Package each component in ./lib into a .tgz tarball - TODO: Account for multiple packages in lib
      - name: Package built components
        run: |
          cd ./lib
          for dir in */; do
            cd "$dir"
            npm pack
            cd ..
          done

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package }}
          path: ./lib/*.tgz
