# This workflow executes a full dry-run test, which means that all we build and test all @cloudscape-design packages in GitHub.
# This ensures that the changes in the current package do not cause any regressions for its consumers.
name: dry-run

on:
  pull_request:
    branches:
      - main
  workflow_call:

permissions:
  contents: read

defaults:
  run:
    shell: bash

env:
  # Disable Husky in CI
  # https://typicode.github.io/husky/how-to.html#ci-server-and-docker
  HUSKY: 0

jobs:
  createBuildTree:
    name: Create build tree
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix-output.outputs.matrix }}    
    steps:
      - uses: cloudscape-design/actions/.github/actions/create-build-tree@dry-run
        id: set-matrix-output
        with:
          package: ${{ github.event.repository.full_name }}
  build_level_0:
    needs: createBuildTree
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.createBuildTree.outputs.matrix)['0'] }}
    steps:
      - name: Build Level 0
        uses: cloudscape-design/actions/.github/actions/build-package@dry-run
        with:
          package: ${{ matrix.package }}
  build_level_1:
    needs: build_level_0
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.createBuildTree.outputs.matrix)['1'] }}
    steps:
      - name: Build Level 1
        uses: cloudscape-design/actions/.github/actions/build-package@dry-run
        with:
          package: ${{ matrix.package }}
          dependencies:  ${{ fromJson(needs.createBuildTree.outputs.matrix)['0'] }}    

