name: release-gh-notes

on:
  workflow_call:
    inputs:
      version:
        required: true
        description: npm version for this release
        type: string
      commit:
        required: true
        description: commit to generate release notes
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit }}
          fetch-depth: 0
      - name: Replace version in package.json
        run: |
          package_json="$(jq --arg version "$VERSION" '.version = $version' package.json)" && \
          echo -E "${package_json}" > package.json && \
          cat package.json
        env:
          VERSION: ${{ github.event.inputs.version }}
      - name: Generate changelog
        run: npx conventional-changelog-cli@2 -i CHANGELOG.md -s -p conventionalcommits
      - name: Get number of lines in CHANGELOG.md
        id: changelog
        run: echo "changelog_lines=$(wc -l < "CHANGELOG.md" | sed  s/\ //g)" >> $GITHUB_OUTPUT
        shell: bash
      - name: Add empty release note
        run: echo "No customer visible changes in this release" >> CHANGELOG.md
        if: ${{ steps.changelog.outputs.changelog_lines <= 2 }}
      - name: Create Release
        run: gh release create "$VERSION" -F CHANGELOG.md --target "$COMMIT" --title "Release $VERSION"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.event.inputs.version }}
          COMMIT: ${{ github.event.inputs.commit }}
