# This workflow releases the current package to a dedicated private CodeArtifact repository.
# One repository may publish more than one package. For more details refer to the release-package Action.
name: release

on:
  workflow_call:
    inputs:
      publish-packages:
        description: Comma-separated list of sub-folders to publish
        type: string
        required: false
      publish-artifacts:
        description: Root folder to publish build artifacts
        type: string
        required: false
        default: './'
      skip-test:
        type: boolean
        description: Skip tests
        required: false
        default: false

permissions:
  id-token: write
  contents: read

jobs:
  release:
    concurrency: release-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install --force

      - run: npm run build

      - run: npm run test
        if: ${{ inputs.skip-test == false }}

      - name: Publish release artifacts
        id: upload-release
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: |
            ${{ inputs.publish-artifacts }}
            !.git
            !.github
            !node_modules
            !coverage
        # TODO call the build
      - name: Run CodeBuild
        run: |
          echo https://api.github.com/repos/$AWSUI_REPO/actions/artifacts/$AWSUI_ARTIFACT_ID/zip
        env:
          AWSUI_REPO: ${{ github.repository }}
          AWSUI_COMMIT: ${{ github.sha }}
          AWSUI_ARTIFACT_ID: ${{ steps.upload-release.outputs.artifact-id }}
          AWSUI_OVERRIDE_TARGET_BRANCH: ${{ github.ref_name }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_CODEARTIFACT_ROLE }}
          aws-region: us-west-2
      - name: Login and configure codeartifact
        env:
          CODE_ARTIFACT_REPO: ${{ startsWith(github.ref_name, 'dev-v3-') && format('AwsUI-Artifacts-{0}', github.ref_name) || 'github-artifacts' }}
        run: |
          echo Logging into repository $CODE_ARTIFACT_REPO
          aws codeartifact login --tool npm --repository $CODE_ARTIFACT_REPO --domain awsui --domain-owner ${{ secrets.AWS_ACCOUNT_ID }} --region us-west-2 --namespace @cloudscape-design
      - name: Release package to private CodeArtifact
        uses: cloudscape-design/actions/.github/actions/release-package@main
        with:
          publish-packages: ${{ inputs.publish-packages }}
